server:
  port: 8081
# 设置日志打印
# logging.level.root: 日志级别
# logging.pattern.console: 日志输出格式
  # %m为消息
  # %n为换行
  # %p 级别
  # %t 为线程名 %16t 则线程名占16位
  # %clr 是添加颜色
  # 例如 %clr（%m） 则日志消息带有颜色
# logging.file.name: 记录日志到文件
# logging.file.logback.rollingpolicy.max-file-size: 日志文件大小
# logging.file.logback.rollingpolicy.file-name-pattern: 超过最大后，重新创建日志文件名称
logging:
  level:
    root: info
  pattern:
    console: "%d - %m %n"
  file:
    name: E:\myJavaProject\springCloudAlibaba_tl\log\server.log
  logback:
    rollingpolicy:
      max-file-size: 4MB
      file-name-pattern: E:\myJavaProject\springCloudAlibaba_tl\log\server.%d{yyyy-MM-dd}.%i.log
spring:
  application:
    name: sentinel-demo
  cloud:
    nacos:
      server-addr: www.yuqn.xyz:8848
      discovery:
        username: nacos
        password: idiot_Yuqn@123
        namespace: public
    sentinel:
      transport:
        dashboard: 127.0.0.1:9000
